name: Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: make install-dependencies
      - name: lint web
        run: make lint-web
      - name: build web assets # built web assets must exist or lint will fail
        run : make build-web
      - name: lint daemon
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ darwin, linux, windows ]
        arch: [ arm64, amd64 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: v1.17
      - name: build ${{ matrix.os }}/${{ matrix.arch }}
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make build-web static